name: CI

on: [push]

jobs:
  build:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: 8398a7
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/8398a7/api-abilitysheet/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
